({
    afterRender: function (component, helper) {
         this.superAfterRender();
         var config = component.get("v.config");
        var region =(config)?config.Region:'';
          var action = component.get("c.getBcConnectConfigs");
            action.setCallback(this, function(response){
                if(response.getState() === 'SUCCESS'){
                    var results = response.getReturnValue();
                    region = results.Region;
                } 
            });
        $A.enqueueAction(action);
        // adds a listener for all events generated by the iframe softphone.
        window.addEventListener('message', event => {
            
            // IMPORTANT: check the origin of the data! staging.dev
            if (region.startsWith(event.origin)) { 
            	const newEvent = JSON.parse(JSON.stringify(event.data));
            	
            	//console.log(`event type == ${newEvent.event}`);
        		//console.log(newEvent);
            	helper.handleEventsFromIframe(component,newEvent);
            	
            }else{
                //console.log(JSON.parse(JSON.stringify(event.data)));
			}
		}); 


	},
})